baseURL = 'https://hirokit.daar.cz'
languageCode = 'en-us'
title = 'Hirokit'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookSearch = true

[markup.goldmark.renderer]
unsafe = true